version: "3.9"

services:
  app:
    build:
      context: .  # Указываем путь к директории с Dockerfile
      dockerfile: Dockerfile
    container_name: python_app
    volumes:
      - .:/app  # Монтируем локальную директорию внутрь контейнера для удобства разработки
    ports:
      - "8000:8000"  # Пробрасываем порты (если приложение запускается на 8000 порту)
    environment:
      - PYTHONUNBUFFERED=1  # Гарантирует, что вывод в логах будет доступен сразу
    command: python main.py  # Переопределяем команду на запуск приложения
